# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='event time')),
            ],
        ),
        migrations.CreateModel(
            name='LiveState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('total_power_generation', models.IntegerField(default=0)),
                ('total_power_demand', models.IntegerField(default=0)),
                ('average_efficiency', models.DecimalField(decimal_places=5, max_digits=15)),
                ('pv_output', models.IntegerField(default=0)),
                ('battery_storage', models.IntegerField(default=0)),
                ('network_healthy', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
